version: "3.1"

services:
  client:
    build: .
    volumes:
      - "./../client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
    stdin_open: true

  api:
    build: .
    volumes:
      - "./../api:/app"
    ports:
      - "4001:4001"
    depends_on:
      - db
    restart: always

  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/db/:/var/lib/mysql
    env_file:
      - ./db/db-config.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=Azerty123!
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
